import React from 'react';

export type IconProps = React.SVGProps<SVGSVGElement> & {
	size?: number;
	role?: string;
};

// Exports
export { MoonIcon } from './moon-icon';
export { SunIcon } from './sun-icon';
export { ChevronsUpDownIcon } from './chevrons-up-down-icon';
export { ArrowLeftIcon } from './arrow-left-icon';
export { CircleAlertIcon } from './circle-alert-icon';
export { CircleCheckIcon } from './circle-check-icon';
export { TriangleAlertIcon } from './triangle-alert-icon';
export { InfoIcon } from './info-icon';
export { LoaderCircleIcon } from './loader-circle-icon';
export { MenuIcon } from './menu-icon';
export { CrossIcon } from './cross-icon';
export { NextjsIcon } from './nextjs-icon';
export { ReactIcon } from './react-icon';
export { DrizzleIcon } from './drizzle-icon';
export { ShadcnIcon } from './shadcn-icon';
export { LuciaIcon } from './lucia-icon';
export { StripeIcon } from './stripe-icon';
export { SettingsIcon } from './settings-icon';
export { HomeIcon } from './home-icon';
export { AccountIcon } from './account-icon';
export { ExternalLinkIcon } from './external-link-icon';
export { GoogleIcon } from './google-icon';
export { GithubIcon } from './github-icon';
export { ChevronDownIcon } from './chevron-down-icon';
export { PlusIcon } from './plus-icon';
export { LinkIcon } from './link-icon';
export { EyeIcon } from './eye-icon';
export { LogoutIcon } from './logout-icon';
export { ShareIcon } from './share-icon';
export { GripVerticalIcon } from './grip-vertical-icon';
export { TrashIcon } from './trash-icon';
export { CheckIcon } from './check-icon';
export { ChevronUpIcon } from './chevron-up-icon';
export { SearchIcon } from './search-icon';
export { YoutubeIcon } from './youtube-icon';
export { ArrowRightIcon } from './arrow-right-icon';
export { FacebookIcon } from './facebook-icon';
export { LinkedinIcon } from './linkedin-icon';
export { XIcon } from './x-icon';
export { TwitchIcon } from './twitch-icon';
export { DevtoIcon } from './devto-icon';
export { CodewarsIcon } from './codewars-icon';
export { FreecodecampIcon } from './freecodecamp-icon';
export { GitlabIcon } from './gitlab-icon';
export { HashnodeIcon } from './hashnode-icon';
export { StackoverflowIcon } from './stackoverflow-icon';
